### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by ragouel** [u-235/edytornc#13]
Qt5 version: 5.15.0
Linux version : 5.4.48
gcc version: 10.1.0
cmake version: 3.17.3

Run with
`qmake PREFIX="/usr" -r`
`make`

<pre><code>/home/crow/Git/BROKEN/edytornc-git/src/edytornc/common.pri:1: Extra characters after test expression.
/home/crow/Git/BROKEN/edytornc-git/src/edytornc/common.pri:104: Assignment needs exactly one word on the left hand side.
/home/crow/Git/BROKEN/edytornc-git/src/edytornc/common.pri:207: Extra characters after test expression.
/home/crow/Git/BROKEN/edytornc-git/src/edytornc/edytornc.pro:40: 'findFiles' is not a recognized replace function.
Reading /home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty/3rdparty.pro
 Reading /home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty/kdiff3/kdiff3.pro
/home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty/kdiff3/kdiff3.pro:37: 'tsFiles' is not a recognized replace function.
 Reading /home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty/qtsingleapplication/qtsingleapplication.pro
Reading /home/crow/Git/BROKEN/edytornc-git/src/edytornc/src/src.pro
/home/crow/Git/BROKEN/edytornc-git/src/edytornc/src/src.pro:110: 'tsFiles' is not a recognized replace function.
lrelease /*.ts
lrelease error: Cannot open /*.ts: No such file or directory
make: *** [Makefile:437: FORCE] Error 1</code></pre>

**Comment by u-235** [comment]
And what have you done to fix that?

**Comment by ragouel** [comment]
Nothing, didn't have the time.
