### ISSUE TITLE
Compilation failure with GCC version >= 11: "ordered comparison of pointer with integer zero"

### ISSUE THREAD

**Issue by zmaile** [u-235/edytornc#15]
GCC11 has deprecated a feature: Ordered pointer comparison with integer
[Details](https://www.gnu.org/software/gcc/gcc-11/porting_to.html)

This is causing compilation failure on Linux systems with GCC version >= 11 (Manjaro in my case). I'm also unsure how to force a specific version of GCC in qmake to workaround the issue, so I haven't tested that option

[make.log](https://github.com/u-235/edytornc/files/9180616/make.log)
.

**Comment by u-235** [comment]
Hi.  
Thanks for the detailed bug report. It will definitely be fixed, but unfortunately I don't have time right now.

**Comment by u-235** [comment]
I hope that the bcabfb4 fixes this issue.

**Comment by zmaile** [comment]
It did, thank you.
