### ISSUE TITLE
Serial "Send current file" doesn't work

### ISSUE THREAD

**Issue by zmaile** [u-235/edytornc#16]
Pressing the button either segfaults the program, or has no effect.
I compiled from source, as per the README instructions on two devices running Linux Mint and Manjaro. The problem is identical on both.

I looked through the source code, and i think I found the culprit:
src/edytornc.cpp line 4107. I changed the comparison from
`if (activeWindow != nullptr) {`
to
`if (activeWindow == nullptr) {`
and now it seems to work after a recompile.

**Comment by u-235** [comment]
Hi.
Thank you for your interest in the project. I most likely made some similar mistakes in the bcabfb48 commit. I will fix it later.

**Comment by u-235** [comment]
Fixed in 3200512
