### ISSUE TITLE
Feature request: Disable date-updating macro

### ISSUE THREAD

**Issue by zmaile** [u-235/edytornc#17]
My gcode file headers usually have a drawing number and date in it. However, that date is overwritten on save with the current date, which has caught me out a few times.
Would it be possible to make an option in edit > configuration to toggle this feature on/off?

**Comment by u-235** [comment]
Hi.
Thanks for the feedback and the interesting suggestion. It won't be hard to implement, but unfortunately I don't have much free time right now. I will most likely do it in early January.

**Comment by u-235** [comment]
I added this option in 57f79f1
![screenshot](https://user-images.githubusercontent.com/5675211/210772019-6941893a-40a4-4e17-8043-2f9e6b1245bd.png)

**Comment by zmaile** [comment]
You the man
