### ISSUE TITLE
save deployed positions for ‚‚serial port toolbar‚‚ ‚‚find‚‚ ...

### ISSUE THREAD

**Issue by WD50** [u-235/edytornc#21]
(Win11)
In the old EdytorNC by artur231 (r162), when I place positions for ‚‚serial port toolbar‚‚ ‚‚find‚‚ ... , they stay in place the next time I open the EdytorNC.
In the EdytorNC by you made on 03/09/2023, everything returns to the initial position next time.

some lock toolbar position? save ui on exit?

**Comment by u-235** [comment]
I think I've fixed this bug in the [bugfix branch](https://github.com/u-235/edytornc/tree/bugfix) branch. Can you check if the fixed version works?

**Comment by WD50** [comment]
I just compiled the version from:
https://github.com/u-235/edytornc/archive/refs/heads/bugfix.zip
and no it doesn't stay where i put toolbar.
‚‚find‚‚ always goes down and the ‚‚serial port toolbar‚‚ that I place on the right goes up at the end, means it remains open but not in position

**Comment by u-235** [comment]
This error no longer occurs in Windows 7 and unfortunately there is no idea what else can be fixed yet. Are other settings such as recent files, main window position etc. saved?

**Comment by WD50** [comment]
ok good news
I know I'm far from good at compiling so I installed MSYS2 from scratch. This time I used command:

```
cd ~
wget https://github.com/u-235/edytornc/archive/refs/heads/bugfix.zip
unzip bugfix.zip
cd edytornc-bugfix
qmake -r
make -j4
```
this time I got everything ok and now the application remembers the positions for the toolbar.
I think I didn't write the command correctly last time and MSYS2 mixed up master and bugfis
sorry it's my mistake

**Comment by u-235** [comment]
OK, thanks for the help. I moved the commit with the fixes to the `master` branch and deleted the `bugfix` branch.
