### ISSUE TITLE
Build failure 3rdparty

### ISSUE THREAD

**Issue by ragouel** [u-235/edytornc#6]
OS: Arch Linux 4.20.13-arch1-1-ARCH
QT 5.14.2

Reproduce by running inside `edytornc`

-   qmake PREFIX="/usr"
-   make

<pre><code>cd 3rdparty/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/crow/Git/AUR/edytornc-git/src/edytornc/3rdparty/3rdparty.pro PREFIX=/usr ) && make -f Makefile 
make[1]: Entering directory '/home/crow/Git/AUR/edytornc-git/src/edytornc/3rdparty'
cd kdiff3/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/crow/Git/AUR/edytornc-git/src/edytornc/3rdparty/kdiff3/kdiff3.pro ) && make -f Makefile 
make[2]: Entering directory '/home/crow/Git/AUR/edytornc-git/src/edytornc/3rdparty/kdiff3'
lupdate kdiff3.pro
/home/crow/Git/AUR/edytornc-git/src/edytornc/3rdparty/kdiff3/mergeresultwindow.cpp:3059: Discarding unconsumed meta data
Updating '../../lang/kdiff3_pl.ts'...
    Found 36 source text(s) (0 new and 36 already existing)
Updating '../../lang/kdiff3_ca.ts'...
    Found 36 source text(s) (0 new and 36 already existing)
Updating '../../lang/kdiff3_de.ts'...
    Found 36 source text(s) (0 new and 36 already existing)
Updating '../../lang/kdiff3_fi.ts'...
    Found 36 source text(s) (0 new and 36 already existing)
Updating '../../lang/kdiff3_cs.ts'...
    Found 36 source text(s) (0 new and 36 already existing)
Updating '../../lang/kdiff3_es.ts'...
    Found 36 source text(s) (0 new and 36 already existing)
rm -f ../lib/linux/libkdiff3.a
ar cqs ../lib/linux/libkdiff3.a ../../build/release/kdiff3/obj/difftextwindow.o ../../build/release/kdiff3/obj/diff.o ../../build/release/kdiff3/obj/merger.o ../../build/release/kdiff3/obj/optiondialog.o ../../build/release/kdiff3/obj/common.o ../../build/release/kdiff3/obj/fileaccess.o ../../build/release/kdiff3/obj/kdiff3.o ../../build/release/kdiff3/obj/gnudiff_xmalloc.o ../../build/release/kdiff3/obj/gnudiff_io.o ../../build/release/kdiff3/obj/gnudiff_analyze.o ../../build/release/kdiff3/obj/pdiff.o ../../build/release/kdiff3/obj/mergeresultwindow.o ../../build/release/kdiff3/obj/moc_difftextwindow.o ../../build/release/kdiff3/obj/moc_diff.o ../../build/release/kdiff3/obj/moc_optiondialog.o ../../build/release/kdiff3/obj/moc_fileaccess.o ../../build/release/kdiff3/obj/moc_kdiff3.o ../../build/release/kdiff3/obj/moc_mergeresultwindow.o
make[2]: Leaving directory '/home/crow/Git/AUR/edytornc-git/src/edytornc/3rdparty/kdiff3'
cd qtsingleapplication/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home
/crow/Git/AUR/edytornc-git/src/edytornc/3rdparty/qtsingleapplication/qtsingleapplication.pro ) && make -f Makefile 
make[2]: Entering directory '/home/crow/Git/AUR/edytornc-git/src/edytornc/3rdparty/qtsingleapplication'
g++ -c -pipe -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fPIC -std=gnu++11 -D_REENTRANT -Wall -Wextra -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I/home/crow/Git/AUR/edytornc-git/src/edytornc//include/ -I../../3rdparty -I../include -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -I../../build/release/qtsingleapplication/moc -I/usr/lib/qt/mkspecs/linux-g++ -o ../../build/release/qtsingleapplication/obj/qtsingleapplication.o qtsingleapplication.cpp
Assembler messages:
Fatal error: can't create ../../build/release/qtsingleapplication/obj/qtsingleapplication.o: No such file or directory
make[2]: *** [Makefile:621: ../../build/release/qtsingleapplication/obj/qtsingleapplication.o] Error 2
make[2]: Leaving directory '/home/crow/Git/AUR/edytornc-git/src/edytornc/3rdparty/qtsingleapplication'
make[1]: *** [Makefile:73: sub-qtsingleapplication-make_first] Error 2
make[1]: Leaving directory '/home/crow/Git/AUR/edytornc-git/src/edytornc/3rdparty'
make: *** [Makefile:48: sub-3rdparty-make_first-ordered] Error 2
</code></pre>

**Comment by u-235** [comment]
### Hi, Dimitris.

Thank you for the bug report. The script didn't create a directory to build, but I didn't notice it because I haven't built a project in an empty directory for a long time. 8594dce is fixing this bug.

Best regards, Николай.
