### ISSUE TITLE
Build fails with error 'make: *** [Makefile:91: sub-src-make_first-ordered] Error 2'

### ISSUE THREAD

**Issue by ragouel** [u-235/edytornc#7]
Build fails during `make` this time.

OS: Arch Linux 4.20.13-arch1-1-ARCH
QT 5.14.2
GNU Make 4.3

Reproduce by running inside `edytornc`

- [x] qmake PREFIX="/usr"
- [ ] make

[build_error.log](https://github.com/u-235/edytornc/files/4562694/build_error.log)
[build_error2.log](https://github.com/u-235/edytornc/files/4562713/build_error2.log)

<pre><code>edytornc.cpp:1338:90: warning: ‘static QString EdytorNc::trUtf8(const char*, const char*, int)’ is deprecated [-Wdeprecated-declarations]
 1338 |                               "MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.</i>"));
      |                                                                                          ^
In file included from /usr/include/qt/QtGui/qwindowdefs.h:44,
                 from /usr/include/qt/QtGui/qpaintdevice.h:44,
                 from /usr/include/qt/QtGui/qpagedpaintdevice.h:44,
                 from /usr/include/qt/QtPrintSupport/qprinter.h:46,
                 from /usr/include/qt/QtPrintSupport/QPrinter:1,
                 from edytornc.cpp:23:
include/edytornc.h:48:5: note: declared here
   48 |     Q_OBJECT
      |     ^~~~~~~~
edytornc.cpp:1338:90: warning: ‘static QString EdytorNc::trUtf8(const char*, const char*, int)’ is deprecated [-Wdeprecated-declarations]
 1338 |                               "MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.</i>"));
      |                                                                                          ^
In file included from /usr/include/qt/QtGui/qwindowdefs.h:44,
                 from /usr/include/qt/QtGui/qpaintdevice.h:44,
                 from /usr/include/qt/QtGui/qpagedpaintdevice.h:44,
                 from /usr/include/qt/QtPrintSupport/qprinter.h:46,
                 from /usr/include/qt/QtPrintSupport/QPrinter:1,
                 from edytornc.cpp:23:
include/edytornc.h:48:5: note: declared here
   48 |     Q_OBJECT
      |     ^~~~~~~~
make[1]: *** [Makefile:1155: ../build/release/edytornc/obj/edytornc.o] Error 1
make: *** [Makefile:91: sub-src-make_first-ordered] Error 2</code></pre>

**Comment by u-235** [comment]
Hi, Dimitris.
What's your version of the compiler?

**Comment by ragouel** [comment]
QMake version 3.1

**Comment by u-235** [comment]
db8b784
