### ISSUE TITLE
make install fails 'make[1]: *** [Makefile:1436: install_target] Error 3'

### ISSUE THREAD

**Issue by ragouel** [u-235/edytornc#8]
We're getting closer... this time it's `make install`

OS: Arch Linux 4.20.13-arch1-1-ARCH
QT 5.14.2
GNU Make 4.3
QMake version 3.1
gcc version 9.3.0

Reproduce by running inside `edytornc`

- [x] qmake PREFIX="/usr"
- [x] make
- [ ] make DESTDIR="path/to/install" install

<pre><code>cd 3rdparty/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty/3rdparty.pro PREFIX=/usr ) && make -f Makefile install
make[1]: Entering directory '/home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty'
cd kdiff3/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty/kdiff3/kdiff3.pro PREFIX=/usr ) && make -f Makefile install
make[2]: Entering directory '/home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty/kdiff3'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty/kdiff3'
cd qtsingleapplication/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty/qtsingleapplication/qtsingleapplication.pro PREFIX=/usr ) && make -f Makefile install
make[2]: Entering directory '/home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty/qtsingleapplication'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty/qtsingleapplication'
make[1]: Leaving directory '/home/crow/Git/BROKEN/edytornc-git/src/edytornc/3rdparty'
cd src/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/crow/Git/BROKEN/edytornc-git/src/edytornc/src/src.pro PREFIX=/usr ) && make -f Makefile install
make[1]: Entering directory '/home/crow/Git/BROKEN/edytornc-git/src/edytornc/src'
lupdate src.pro
Updating '../lang/edytornc_pl.ts'...
    Found 942 source text(s) (0 new and 942 already existing)
Updating '../lang/edytornc_ca.ts'...
    Found 942 source text(s) (0 new and 942 already existing)
Updating '../lang/edytornc_de.ts'...
    Found 942 source text(s) (0 new and 942 already existing)
Updating '../lang/edytornc_fi.ts'...
    Found 942 source text(s) (0 new and 942 already existing)
Updating '../lang/edytornc_cs_CZ.ts'...
    Found 942 source text(s) (0 new and 942 already existing)
Updating '../lang/edytornc_es.ts'...
    Found 942 source text(s) (0 new and 942 already existing)
lrelease src.pro
Updating '/home/crow/Git/BROKEN/edytornc-git/src/edytornc//lang//edytornc_pl.qm'...
    Generated 794 translation(s) (739 finished and 55 unfinished)
    Ignored 148 untranslated source text(s)
Updating '/home/crow/Git/BROKEN/edytornc-git/src/edytornc//lang//edytornc_ca.qm'...
    Generated 595 translation(s) (485 finished and 110 unfinished)
    Ignored 347 untranslated source text(s)
Updating '/home/crow/Git/BROKEN/edytornc-git/src/edytornc//lang//edytornc_de.qm'...
    Generated 929 translation(s) (926 finished and 3 unfinished)
    Ignored 13 untranslated source text(s)
Updating '/home/crow/Git/BROKEN/edytornc-git/src/edytornc//lang//edytornc_fi.qm'...
    Generated 559 translation(s) (470 finished and 89 unfinished)
    Ignored 383 untranslated source text(s)
Updating '/home/crow/Git/BROKEN/edytornc-git/src/edytornc//lang//edytornc_cs_CZ.qm'...
    Generated 937 translation(s) (934 finished and 3 unfinished)
    Ignored 5 untranslated source text(s)
Updating '/home/crow/Git/BROKEN/edytornc-git/src/edytornc//lang//edytornc_es.qm'...
    Generated 934 translation(s) (934 finished and 0 unfinished)
    Ignored 8 untranslated source text(s)
g++ -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o ../bin/release/edytornc ../build/release/edytornc/obj/edytornc.o ../build/release/edytornc/obj/main.o ../build/release/edytornc/obj/highlighter.o ../build/release/edytornc/obj/mdichild.o ../build/release/edytornc/obj/dialogs.o ../build/release/edytornc/obj/findinf.o ../build/release/edytornc/obj/serialtransmission.o ../build/release/edytornc/obj/basic_interpreter.o ../build/release/edytornc/obj/cleanupdialog.o ../build/release/edytornc/obj/swapaxesdialog.o ../build/release/edytornc/obj/newfiledialog.o ../build/release/edytornc/obj/sessiondialog.o ../build/release/edytornc/obj/serialtransmissiondialog.o ../build/release/edytornc/obj/serialportconfigdialog.o ../build/release/edytornc/obj/commapp.o ../build/release/edytornc/obj/serialportcfghelpdialog.o ../build/release/edytornc/obj/filechecker.o ../build/release/edytornc/obj/longjobhelper.o ../build/release/edytornc/obj/config.o ../build/release/edytornc/obj/medium.o ../build/release/edytornc/obj/medium_linux.o ../build/release/edytornc/obj/qrc_application.o ../build/release/edytornc/obj/moc_edytornc.o ../build/release/edytornc/obj/moc_highlighter.o ../build/release/edytornc/obj/moc_mdichild.o
 ../build/release/edytornc/obj/moc_dialogs.o ../build/release/edytornc/obj/moc_findinf.o ../build/release/edytornc/obj/moc_serialtransmission.o ../build/release/edytornc/obj/moc_cleanupdialog.o ../build/release/edytornc/obj/moc_swapaxesdialog.o ../build/release/edytornc/obj/moc_newfiledialog.o ../build/release/edytornc/obj/moc_sessiondialog.o ../build/release/edytornc/obj/moc_serialtransmissiondialog.o ../build/release/edytornc/obj/moc_serialportconfigdialog.o ../build/release/edytornc/obj/moc_commapp.o ../build/release/edytornc/obj/moc_serialportcfghelpdialog.o ../build/release/edytornc/obj/moc_filechecker.o ../build/release/edytornc/obj/moc_medium.o   -L/home/crow/Git/BROKEN/edytornc-git/src/edytornc//3rdparty//lib/linux// -lkdiff3 -lqtsingleapplication /usr/lib/libQt5PrintSupport.so /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5SerialPort.so /usr/lib/libQt5Network.so /usr/lib/libQt5Core.so -lGL -lpthread   
/usr/bin/qmake -install qinstall -exe ../bin/release/edytornc /usr/local/bin/edytornc
Error copying ../bin/release/edytornc to /usr/local/bin/edytornc: Cannot create /usr/local/bin/edytornc for output
make[1]: *** [Makefile:1436: install_target] Error 3
make[1]: Leaving directory '/home/crow/Git/BROKEN/edytornc-git/src/edytornc/src'
make: *** [Makefile:115: sub-src-install_subtargets-ordered] Error 2</code></pre>

**Comment by u-235** [comment]
Hmm. Are your typing `sudo make install`?

**Comment by ragouel** [comment]
I'm running the command in fakeroot. I'm making a pkbuild for edytornc. Since PREFIX was specified as /usr , it shouldn't try to do anything to /usr/local.

**Comment by u-235** [comment]
Try to commenting or deleting line 139 in src/src.pro
https://github.com/u-235/edytornc/blob/db8b784d6b2b29379f557330b2596ee452170201/src/src.pro#L139

**Comment by ragouel** [comment]
This time it cannot create /usr

<pre><code>/usr/bin/qmake -install qinstall -exe ../bin/release/edytornc /usr/bin/edytornc
Error copying ../bin/release/edytornc to /usr/bin/edytornc: Cannot create /usr/bin/edytornc for output
make[1]: *** [Makefile:1436: install_target] Error 3
make[1]: Leaving directory '/home/crow/Git/BROKEN/edytornc-git/src/edytornc/src'
make: *** [Makefile:115: sub-src-install_subtargets-ordered] Error 2</code></pre>

**Comment by u-235** [comment]
I have no more ideas. I use `sudo make install` and it works. I know that many people don't like this way of installing, but try it as a test.

**Comment by ragouel** [comment]
Can you paste a file tree of the installed package so I can create an install script ?

**Comment by u-235** [comment]
```
install -m 755 -p  /home/crow/Git/BROKEN/edytornc-git/bin/release/edytornc /usr/local/bin/edytornc

install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/lang/edytornc_ca.qm /usr/local/share/edytornc/lang/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/lang/edytornc_cs_CZ.qm /usr/local/share/edytornc/lang/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/lang/edytornc_de.qm /usr/local/share/edytornc/lang/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/lang/edytornc_es.qm /usr/local/share/edytornc/lang/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/lang/edytornc_fi.qm /usr/local/share/edytornc/lang/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/lang/edytornc_pl.qm /usr/local/share/edytornc/lang/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/lang/kdiff3_ca.qm /usr/local/share/edytornc/lang/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/lang/kdiff3_cs.qm /usr/local/share/edytornc/lang/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/lang/kdiff3_de.qm /usr/local/share/edytornc/lang/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/lang/kdiff3_es.qm /usr/local/share/edytornc/lang/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/lang/kdiff3_fi.qm /usr/local/share/edytornc/lang/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/lang/kdiff3_pl.qm /usr/local/share/edytornc/lang/

install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/install/linux/application-x-g-code.xml /usr/local/share/mime/packages/
install -m 755 -p /home/crow/Git/BROKEN/edytornc-git/install/linux/edytornc.desktop /usr/local/share/applications/

install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/install/linux/images/hicolor/32x32/mimetypes/application-x-g-code.png /usr/local/share/icons/hicolor/32x32/mimetypes/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/install/linux/images/hicolor/48x48/apps/edytornc.png /usr/local/share/icons/hicolor/48x48/apps/

install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/0100.nc /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/cnc_tips.txt /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/FANUC0M.nc /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/FANUC0T.nc /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/FLANGE.nc /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/HAAS.nc /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/HK.nc /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/macro7.nc /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/OSP5020M.nc /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/OSP7000L.nc /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/PHILIPS.nc /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/SINUMERIK840D.nc /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/SINUMERIK850.nc /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/examples/TOKARKA.NC /usr/local/share/edytornc/examples/
install -m 644 -p /home/crow/Git/BROKEN/edytornc-git/README.md /usr/local/share/doc/edytornc/
```

**Comment by ragouel** [comment]
Thank you!

**Comment by u-235** [comment]
In build section use `qmake PREFIX="/usr" -r` instead `qmake PREFIX="/usr"`. And in the build section just do `make install`.

```
# Maintainer: Dimitris Kiziridis <ragouel at outlook dot com>

pkgname=edytornc-git
_pkgname=edytornc
pkgver=r188.aed5f68
pkgrel=1
pkgdesc="Text editor for CNC programmers"
arch=('x86_64')
url='https://github.com/u-235/edytornc'
license=('LGPL3')
provides=('edytornc')
depends=('hicolor-icon-theme'
         'qt5-serialport')
makedepends=('git')
source=("git+${url}")
sha256sums=('SKIP')

pkgver() {
  cd "${srcdir}/${_pkgname}"
  ( set -o pipefail
    git describe --long 2>/dev/null | sed 's/\([^-]*-g\)/r\1/;s/-/./g' ||
    printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
  )
}

build() {
  cd "${srcdir}/${_pkgname}"
  qmake PREFIX="/usr" -r
  make
}

package() {
  cd "${srcdir}/${_pkgname}"
  make install
}

```

**Comment by u-235** [comment]
Hi.

If you are still maintaining the [edytornc-git](https://aur.archlinux.org/packages/edytornc-git) package, let me mention that this fork has changed its name. And since the author of the original EdytorNC has put the [repository](https://github.com/artur3/EdytorNC) on GitHub, this may cause confusion.

Also fixed bugs that made it difficult to package the application.
